{{- if .Values.apiserver.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kdp-oam-apiserver.serviceAccountName" . }}
  labels:
    {{- include "kdp-oam-apiserver.labels" . | nindent 4 }}
  {{- with .Values.apiserver.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kdp-oam-operator.fullname" . }}-apiserver
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - get
      - list
  - apiGroups:
      - "*"
    resources:
      - pods
    verbs:
      - get
      - list
      - delete
  - apiGroups:
      - bdc.kdp.io
    resources:
      - applications
    verbs:
      - get
      - list
      - create
      - update
      - delete
  - apiGroups:
      - bdc.kdp.io
    resources:
      - bigdataclusters
    verbs:
      - get
      - list
  - apiGroups:
      - bdc.kdp.io
    resources:
      - contextsecrets
    verbs:
      - get
      - list
  - apiGroups:
      - bdc.kdp.io
    resources:
      - contextsettings
    verbs:
      - get
      - list
  - apiGroups:
      - bdc.kdp.io
    resources:
      - xdefinitions
    verbs:
      - get
      - list
  - verbs:
      - get
      - list
      - create
      - update
      - delete
    apiGroups:
      - cloudshell.cloudtty.io
    resources:
      - cloudshells
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kdp-oam-operator.fullname" . }}-apiserver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kdp-oam-operator.fullname" . }}-apiserver
subjects:
  - kind: ServiceAccount
    name: {{ include "kdp-oam-apiserver.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}