{{- if .Values.apiserver.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kdp-oam-operator.fullname" . }}-apiserver
  labels:
    {{- include "kdp-oam-apiserver.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.apiserver.replicaCount }}
  selector:
    matchLabels:
      {{- include "kdp-oam-apiserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kdp-oam-apiserver.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.images.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kdp-oam-apiserver.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.apiserver.configs}}
      volumes:
        - name: oam-terminal-config
          configMap:
            name: oam-apiserver-terminal-config
            items:
              {{- with .terminalTemplate}}
              - key: terminalTemplate.yaml
                path: terminalTemplate.yaml
              {{- end }}
              {{- with .terminalTransformTemplate}}
              - key: terminalTransformData.json
                path: terminalTransformData.json
              {{- end }}
      {{- end}}
      containers:
        - name: apiserver
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.images.registry }}/{{ .Values.apiserver.image.repository }}:{{ default (include "kdp-oam-operator.defaultTag" .) .Values.apiserver.image.tag }}"
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          args:
            - "apiserver"
            {{- with .Values.apiserver.extraArgs }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.apiserver.service.port }}
              name: server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: server
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: server
            initialDelaySeconds: 5
            periodSeconds: 10
          {{- with .Values.apiserver.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.apiserver.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.apiserver.configs.terminalTemplate }}
          volumeMounts:
            - name: oam-terminal-config
              mountPath: /opt/terminal-config
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}