{{- if .Values.apiserver.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: oam-apiserver-terminal-config
  labels:
    {{- include "kdp-oam-apiserver.labels" . | nindent 4 }}
data:
  {{- with .Values.apiserver.configs }}
  "terminalTemplate.yaml": |
    {{- .terminalTemplate | nindent 4 }}
  "terminalTransformData.json": |-
    {{- .terminalTransformTemplate | nindent 4 }}
  {{- end}}
{{- end}}